name: Rust CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    
    - name: Build
      run: cargo build --verbose --release
    
    - name: Run tests
      run: cargo test --verbose
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: plutonium-key-generator-${{ matrix.os }}
        path: |
          target/release/plutonium-key-generator
          target/release/plutonium-key-generator.exe
